export const GET_MOVIES = "GET_MOVIES";
export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS";
export const GET_MOVIES_STARTED = "GET_MOVIES_STARTED";
export const GET_MOVIES_FAILED = "GET_MOVIES_FAILED";
export const CHANGE_MOVIE_FILTER = "CHANGE_MOVIE_FILTER";
